# Generated by Django 5.2.7 on 2025-11-15 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(null=True)),
                ('permisos', models.JSONField(blank=True, null=True)),
                ('nivel_acceso', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModeloIA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('archivo_iafile_url', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(null=True)),
                ('descripcion_cambios', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('total_herramientas', models.IntegerField(default=0)),
                ('archivo_binario', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modelo_ia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_tecnica', models.TextField(blank=True, null=True)),
                ('instrucciones_uso', models.TextField(blank=True, null=True)),
                ('imagen_referencia_url', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(null=True)),
                ('modelo_ia', models.ForeignKey(blank=True, db_column='modelo_ia_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='web_admin.modeloia')),
            ],
            options={
                'db_table': 'herramienta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReporteAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True)),
                ('parametros_filtro', models.JSONField(blank=True, null=True)),
                ('url_descarga', models.TextField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, default='actual', max_length=50, null=True)),
                ('archivo_binario', models.BinaryField(blank=True, null=True)),
                ('administrador', models.ForeignKey(db_column='administrador_id', on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to='web_admin.administrador')),
            ],
            options={
                'db_table': 'reporte_admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReporteUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField(null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('administrador', models.ForeignKey(blank=True, db_column='administrador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asignados', to='web_admin.administrador')),
                ('herramienta', models.ForeignKey(blank=True, db_column='herramienta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_usuario', to='web_admin.herramienta')),
                ('usuario', models.ForeignKey(db_column='usuario_uid', on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='web_admin.usuario')),
            ],
            options={
                'db_table': 'reporte_usuario',
                'managed': True,
            },
        ),
    ]
